#!/usr/bin/python3

import sys


def factorize(n):
    for m in range(2, n):
        if n % m == 0:
            return m, n // m
    return None, None


def main(file_input):
    with open(file_input, 'r') as file:
        for line in file:
            n = int(line)
            p, q = factorize(n)
            if p is not None and q is not None:
                print(f"{n}={p}*{q}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_input = sys.argv[1]
    main(file_input)
